### ISSUE TITLE
Hyperbolica Web Apps?

### ISSUE THREAD

**Issue by AdrianAntico** [ErikOnBike/CodeParadise#17]
Random question (not an issue). Have you considered creating a web app layout that conforms to hyperbolic geometry? Or even web components that have the property? I was thinking it would be super cool and I'd be able to squeeze so much more inside the app. Sorry if this question is inappropriate here. Not sure how else to get a hold of you to ask.

**Comment by AdrianAntico** [comment]
@ErikOnBike thanks for getting back to me!!

"One idea that pops to mind is something a former colleague came up with for an app we were building: having an object centred in your UI with all directly related objects neatly positioned around it. Pressing the center object opens a kind of 'edit' view on the object. On the 'main' view the user can drag a related item into the center, replacing the center element (and now showing the directly related items of this newly centred object). This UI gives a generic navigation mechanism as a graph in which you can move around. Like a sphere on which all (direct) object relations are shown nearby. Not sure if I explained it well enough."

I believe I'm thinking of something similar. The two main ideas are 1. creating a poincare disc type of component for storing action buttons and 2. having an entire webpage based on a poincare disc properties (probably much harder).  

For the component (which I believe is the easier of the two) the main idea would be to enable having more buttons exposed vs requiring a user to go through a series of clicks to get to a spot on the page to select the buttons of choice. Secondly, it would be super cool and I don't think anyone has done something like that yet (or at least I haven't come across any). The poincare disc would act similarly to those wheel spinners inside cars do to adjust the navigation menu. Each square could hold 1 or more buttons and like you said the surrounding space could be where I put the most related set of buttons. Holonomy would probably be an issue but I'm guessing that can be corrected (like those car rims that don't spin when a car is in motion).  

A little background - Over the last 5 years I have spend all my nights and weekends building out two Automated Machine Learning packages for R and Python (AutoQuant and RetroFit, both open source). Over the last 8 months, I've been building out a web app that hooks up all those functions so a user can point and click their way to solutions. It has some awesome visualization capabilities, data management, data transformations, machine learning, statistical modeling, forecasting, code generation and even the ability to pass along code to run. I have plans to keep adding more tasks, such as new services (e.g. natural language processing modeling) and additional open source frameworks for doing all the above but with additional frameworks that a user can choose from. I think having a truly unique component would not only make for a great user experience but also it could be something that people start talking about, to help the app gain popularity.

**Comment by ErikOnBike** [comment]
Hi @AdrianAntico. Interesting idea definitely, surpasses the idea I mentioned ;-). I like it! :-) An important question is: do you realise that CodeParadise is tightly connected to the Smalltalk (and currently only Pharo) development environment? It does not create standalone Web Components which you can reuse in other environments. If you start to develop using CodeParadise you can incorporate other WebComponents, but it would require some integration. I did this for ChartJS and Shoelace for example. CodeParadise aims to remove the need to write Javascript code and be able to program in Smalltalk both on the server as well as in the client.

If you are okay with developing in Smalltalk:  What is the interaction you envision with such a poincare disc? Like would it drag anywhere you drag within the poincare? Or would it have special handles (like the two white dots in the example you provided)? Any other form? Would there be keyboard support in some way? Use cursor keys to rotate across the two axis?

**Comment by ErikOnBike** [comment]
Hi @AdrianAntico. I have to think about whether I want to invest in such a component at the moment. There are many things I want to add to CodeParadise. And time is limited. Not sure if this would be high up on priority. Since it matches this other idea I mentioned, it does tickle my curiosity, but not sure yet. I'm keeping it open for now. Please inform me if you do continu on another path with this idea. I'll try to report back if I have anything relevant to add. Don't hesitate to add some thoughts and ideas!

**Comment by AdrianAntico** [comment]
Hi @ErikOnBike sounds good. I think reverse engineering the poincare disc on that one website will be the fastest route to getting something put together that I can use. I'll definitely keep you posted about any progress. Thanks for hearing me out!

**Comment by astares** [comment]
@AdrianAntico Did you see https://github.com/ItsNickBarry/hyperbolic-canvas?

**Comment by AdrianAntico** [comment]
@ErikOnBike I didn't see that! Thanks for sharing.

**Comment by ErikOnBike** [comment]
@AdrianAntico :-) please thank @astares since he put the link there! :-)

**Comment by ErikOnBike** [comment]
@AdrianAntico okay if I close this as a current issue? I'm okay with keeping it open if you want to continu discussing this idea as a component within CodeParadise. If you're using another idea/framework/technology I'm eager to learn, since (as said) a similar idea for navigation has been on my mind.
