### ISSUE TITLE
Error when starting up

### ISSUE THREAD

**Issue by FunctionPoint** [ErikOnBike/CodeParadise#28]
Hi Erik, 
I decided to give CP a try but run into an error.
My steps:
- Open a fresh Pharo12 image.
- Import CP with Metacello.
- Select menu Paradise | Reset
Now the two errors in the picture .occur on socker permissions.
What cloud be wrong?
I'm running Windows 11 latest.
Cheers, Richard
![cpError](https://github.com/user-attachments/assets/8092de14-138a-423f-8326-9bc2774978f7)

**Comment by ErikOnBike** [comment]
Hi Richard,

This is probably Windows 11 related or a more strict setup on your machine. I just tried with a fresh image on Windows 10 Pro (which has a fair amount of security features turned on) and it works without a problem. I don't have Windows 11 to test this on. Maybe Windows 11 has stricter security settings? Or do you have some firewall software installed that limits the options of starting a WebSocket server connection? Can you try to 'loosen' or override some of these restrictions (temporarily)?

Hope this helps to pinpoint the issue and hopefully fix it. Please let me know how things go, so I can add an explanation for other users as well.

Cheers,
Erik

**Comment by FunctionPoint** [comment]
Thanks for verifying it's a local problem.
I indeed tried adding Pharo.exe to the firewall exceptions, but that did not help.
I'll investigate further and post the result here.

**Comment by FunctionPoint** [comment]
Hi Erik, it took a while to look.
The error was because there was another webserver running on port 8080.
When I stop that, CP runs fine. :) Sorry for the confusuion.
