### ISSUE TITLE
Spelling typo in disableSecundary/enableSecundary

### ISSUE THREAD

**Issue by macta** [ErikOnBike/CodeParadise#9]
The methods CpHtmlElement>>disableSecundary/enableSecundary should be disableSecondary/enableSecondary

I could possibly submit a pr for this - but a rename touches quite a few places so it might be easier for @ErikOnBike to do this one.

**Comment by ErikOnBike** [comment]
Thanks. Mixed Dutch and English there ;-)
Fixed in https://github.com/ErikOnBike/CodeParadise/commit/87bd8a6ede586030e2689554dd75df796845871c 
Indeed touches quite a few places. (Did not introduce the deprecation rule, assuming it will not be used often. A bit lazy here.)
